# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06d0f0a0137afd1fa13407a702a933d250b38dcf6b71dceedf755921ce75463a33369898dede8a9ecf797840cf1fce39e586a17008ceead689259db626a94f89

test:
  secret_key_base: a1b6698d2a9ccc8fc1541c2da959b356a5777ea6af4278c99cbf43eb668ee2bf32d85011f535cf31e26a4df92f05d88e82e55b3622267fbd0fb9906ec9208fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
